name: CI-production

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: '${{ secrets.PAT }}'

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test --info --stacktrace --no-daemon

      - name: Docker login
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set image tag
        if: github.event_name == 'push'
        id: vars
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build Docker image
        if: github.event_name == 'push'
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/wedit-be:${{ env.IMAGE_TAG }} .

      - name: Push to Docker Hub
        if: github.event_name == 'push'
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/wedit-be:${{ env.IMAGE_TAG }}

      - name: Checkout manifest repository
        if: github.event_name == 'push'
        uses: actions/checkout@v4
        with:
          repository: 'wedit-official/wedit-manifest'
          token: ${{ secrets.PAT }}
          path: 'manifest'

      - name: Update deployment.yml
        if: github.event_name == 'push'
        run: |
          sed -i "s|image:.*|image: ${{ secrets.DOCKERHUB_USERNAME }}/wedit-be:${{ env.IMAGE_TAG }}|g" manifest/production/deployment.yaml
          
          # 변경사항 확인
          echo "Updated deployment.yml: "
          cat manifest/production/deployment.yaml

      - name: Commit and push manifest changes
        if: github.event_name == 'push'
        run: |
          cd manifest
          git config --local user.email "taque88@naver.com"
          git config --local user.name "wien0128"
          git add production/deployment.yaml
          git commit -m "Update production image to ${{ env.IMAGE_TAG }}" || exit 0
          git push origin main